### ISSUE TITLE
Style Directory App according to Chicommons style guide

### ISSUE THREAD

**Issue by laredotornado** [chicommons/maps#10]
[CCC-Style Guide-Ver 1.0.pdf](https://github.com/chicommons/maps/files/5172087/CCC-Style.Guide-Ver.1.0.pdf)

Page 14 of the guide contains style descriptions that we want to apply to the app.  Specifically ...

Blue # 4  (text on buttons and page background)
Teal (for header text)
Turquoise (for button backgrounds)

**Comment by kevinfergus** [comment]
hello!

**Comment by kevinfergus** [comment]
do we want the changes for the nav bar as well or just the submit and clear buttons?

**Comment by laredotornado** [comment]
We had a few comment from Steve . Could you address these ...

- The background in the header and body needs to be the standard  yellow background: #fffcf5
- Not sure the fonts are correct.  Can you validate that the menus are in Allegera Sans and that the body text is in Ubuntu?
- The buttons do not change from #2295a2 to #124e54 on hover or select.

Thanks, -
