### ISSUE TITLE
Frontend: Multi-select menu incorrectly includes "Select" first option

### ISSUE THREAD

**Issue by laredotornado** [chicommons/maps#100]
If you look at the multi-select menu here

https://prod.chicommons.coop/directory-additions-updates

you'll notice that the "Coop Type" field shows a "Select" option even though it is multi-select.  Ideally, there shouldn't be a "Select" option for multi-select menus (only single select menus)

<img width="444" alt="Screen Shot 2021-06-27 at 2 46 01 PM" src="https://user-images.githubusercontent.com/14842313/123557501-b512ce80-d756-11eb-92ef-7286964fe5ba.png">

**Comment by SteveEdiger** [comment]
Where are these pulling from, is the db or the spreadsheet?  We want to normalize the case on each entry.

**Comment by DaveyDevs** [comment]
Just updated to remove the "select" and created a pull request.
