### ISSUE TITLE
Frontend: Add a couple of new breakpoints to search page

### ISSUE THREAD

**Issue by ozzysChiefDataScientist** [chicommons/maps#110]
We need to add breakpoints on
https://prod.chicommons.coop/search
for the following screen widths:
1140, 992, 768

**Comment by ozzysChiefDataScientist** [comment]
Have street, city postal code on one line. County, state, enabled on one line.

**Comment by ozzysChiefDataScientist** [comment]
Submitted PR: https://github.com/chicommons/maps/pull/113

**Comment by laredotornado** [comment]
merged
