### ISSUE TITLE
Upon successful form submission, remove any previous error messages

### ISSUE THREAD

**Issue by laredotornado** [chicommons/maps#124]
Steps to reproduce:

1. Visit the directory add entity link -- https://prod.chicommons.coop/directory-additions-updates
2. Click "Submit" at the bottom without filling in any data.  You'll see some error warnings:

<img width="712" alt="Screen Shot 2021-08-08 at 1 22 24 PM" src="https://user-images.githubusercontent.com/14842313/128641940-502b707e-a7f9-44f4-b6c3-420f57abb63b.png">

3. Fill in the missing data and submit the form.

Notice taht despite the fact the form submission succeeds (in your network tab, observe the 201 response from the POST request upon submitting the form), the error warnings remain.  These shoudl be cleared upon successful form submission.

**Comment by DaveyDevs** [comment]
Just submitted a pull request for this issue. Thanks!
