### ISSUE TITLE
Need to indicate required fields on add/edit form

### ISSUE THREAD

**Issue by laredotornado** [chicommons/maps#14]
Currently our add/edit form doesn't have the little red "*" (asterisk) next to the required fields ...

<img width="454" alt="Screen Shot 2020-09-24 at 2 15 11 PM" src="https://user-images.githubusercontent.com/14842313/94189656-a23e3700-fe70-11ea-974b-f11117d5cc0e.png">

We need to add the required asterisk next to every field on this page except "Web site".

**Comment by DaveyDevs** [comment]
Hey!
