### ISSUE TITLE
Unable to select multiple values on Entity Types field in Add form

### ISSUE THREAD

**Issue by laredotornado** [chicommons/maps#145]
On this page

https://prod.chicommons.coop/directory-additions-updates

The field "Entity Types" is a multiple selection box, but it is currently only possible to select one value.  It should be possible to select (and submit) multiple values.

**Comment by laredotornado** [comment]
cc: @DaveyDevs

**Comment by DaveyDevs** [comment]
Hey @laredotornado!

Currently, the multi-select is set up to use the browser defaults. For example, holding down "control" on a desktop while clicking each item will let you select multiple whereas mobile (at least for iphone) adds check marks as you go through and select each one. 

I believe there are some libraries that might help us find something that doesn't require the keyboard on desktop. When possible, can you let me know if the "multi" example here might be what we'd be looking for? https://react-select.com/home

**Comment by laredotornado** [comment]
Oops, didn't realize that.  Yup, I can select multiple now.  Closing this issue.  cc: @kevinjung2
