### ISSUE TITLE
On search | submit | select entity | edit, not all fields are pulled from spreadsheet record.

### ISSUE THREAD

**Issue by SteveEdiger** [chicommons/maps#146]
When searching and editing an entity not all fields are pulled from the spreadsheet.   Specifically eng-desc does not show. See ID 487, Logan Square Housing Coop, for an example.  I would bet that the other description paragraphs don't get pullled over either.

**Comment by laredotornado** [comment]
Hi @SteveEdiger , to make this a little easier for developers to digest, I've created this backend ticket -- https://github.com/chicommons/maps/issues/147 .  I'm going to close out this one unless you feel I've missed something.

**Comment by SteveEdiger** [comment]
Yes you can close this, but please copy labels when doing something like this.
