### ISSUE TITLE
Frontend: Add Cancel button to directory/search pages

### ISSUE THREAD

**Issue by laredotornado** [chicommons/maps#154]
On the add page

https://prod.chicommons.coop/directory-additions-updates

as well as the "Search" page

https://prod.chicommons.coop/search

we wish to add a "cancel" button alongside the submit buttons.  Clicking "Cancel" should return the user to the previous screen.  Open to how you would want to implement this, history.back() would be a perfectly fine implementation if you would like to go this way.

**Comment by DaveyDevs** [comment]
Hey @laredotornado! I have the functionality working but wanted to check in on the styles. Would we want to have the cancel button be an inverted color scheme, for example. Also, should we have the buttons on the search and add page look the same? Happy to make them consistent if desired.

**Comment by laredotornado** [comment]
These are good questions.  @SteveEdiger , do you have a preference?

**Comment by SteveEdiger** [comment]
The style guide and checking the chicommons.coop site for examples should guide you. I've attached the style guide.  Please keep it and refer to it when questions about formatting arise.Steve EdigerFounding Worker-Owner, ChiCommons LWCAwww.chicommons.coop ---- On Mon, 11 Oct 2021 20:16:10 -0500  ***@***.***  wrote ----
These are good questions.  @SteveEdiger , do you have a preference?

**Comment by laredotornado** [comment]
Some notes from @SteveEdiger 

- Cancel should be have a narrow box around it and it should be adjacent to the action (to the right of the action) on the same line.
- Cancel action from Add is ok to go to home
- Cancel action from Search can go to home
- Cancel action from Search / Edit should go back to Search
