### ISSUE TITLE
Frontend: Need a 404 page for routes that don't exist.

### ISSUE THREAD

**Issue by laredotornado** [chicommons/maps#165]
Currently in our app, if you enter a path to a route that doens't exist, e.g.

https://prod.chicommons.coop/bad-page

you just see a blank page with our nav bar.  For a better user experience, it would be better if we had a more traditional "Page not found" component, explaining that the path they are looking for does not exist.

As we are working on a new version of the app, base your PR/branch off the "authentication" branch, as opposed to the "master" branch.

**Comment by maxgraziano** [comment]
Duplicate of #236
