### ISSUE TITLE
Frontend: Email address not being populated properly

### ISSUE THREAD

**Issue by laredotornado** [chicommons/maps#183]
Be sure you are on the authentication branch
```
git checkout authentication
```

then observe that after you add a coop (http://localhost:3001/directory-additions-updates for Docker, http://localhost:3000/directory-additions-updates without Docker) with a valid email, when you search for that coop here -- http://localhost:3000/search 
<img width="971" alt="Screen Shot 2022-04-09 at 7 03 11 PM" src="https://user-images.githubusercontent.com/14842313/162595679-c2aca7a9-b5f8-4edb-b716-1ca07d28a05c.png">

by entering the name, clicking "Submit,"and then clicking the pencil icon next to the coop that is returned, you will see on the following screen, the email address is not displayed correctly
<img width="389" alt="Screen Shot 2022-04-09 at 7 05 24 PM" src="https://user-images.githubusercontent.com/14842313/162595673-faf61853-3662-42cd-aaf1-e3d0694b80c2.png">

**Comment by domdelorenzo** [comment]
Hi @laredotornado . I'll take this. I think my [PR 187](https://github.com/chicommons/maps/pull/187) addresses it.

**Comment by laredotornado** [comment]
Thanks @domdelorenzo !  I merged your PR.  Appreciate the quick work.
