### ISSUE TITLE
Frontend: Updating an existing coop does not succeed if you leave "Entity Types" field unchanged

### ISSUE THREAD

**Issue by laredotornado** [chicommons/maps#184]
Be sure you are on the authentication branch

```
git checkout authentication
```

then observe that after you add a coop (http://localhost:3001/directory-additions-updates for Docker, http://localhost:3000/directory-additions-updates without Docker) with a valid email, when you search for that coop here -- http://localhost:3000/search

<img width="971" alt="Screen Shot 2022-04-09 at 7 03 11 PM" src="https://user-images.githubusercontent.com/14842313/162595884-096a3ef6-7f25-4fb9-b171-0cb73b85da8c.png">

by entering the name, clicking "Submit,"and then clicking the pencil icon next to the coop that is returned, you will see a screen where you can edit the fields of the coop.  Type a valid email (there is a current bug where the email is not returned properly), and then click "Send Addition/Update".  You iwll notice the following screen.

<img width="799" alt="Screen Shot 2022-04-09 at 7 13 35 PM" src="https://user-images.githubusercontent.com/14842313/162595875-75a42a9a-2e2d-415c-8652-2ef8a222ee2a.png">

Notice in your "Network" tab of your dev console, there is an error returned,

```
{
	"types": [
		{
			"name": [
				"Not a valid string."
			]
		}
	]
}
```

This means the "Entity Types" field was not submitted to the backend properly.  However, notice that if you change the "Entity Types" field by clicking on any other option and then clicking the button to submit, the form submission succeeds.

<img width="851" alt="Screen Shot 2022-04-09 at 7 17 55 PM" src="https://user-images.githubusercontent.com/14842313/162595867-c929ab61-fef9-4ba9-9367-7a851efae2f3.png">

We need to be able to submit an update even if we don't change the "Entity Types" field.

**Comment by domdelorenzo** [comment]
Hey @laredotornado - I think my PR [#187 ](https://github.com/chicommons/maps/pull/187) addresses this, but I noticed that every time I submit an update, it creates a new entity instead of updating the existing entity. Is that intended behavior?

**Comment by laredotornado** [comment]
I noticed that over the weekend as well.  If you update your code with the latest from the authentication branch (on the main repo), you shoudl see a fix for this.

**Comment by laredotornado** [comment]
Thanks to @domdelorenzo for taking care of this one.
