### ISSUE TITLE
Onboarding:  Windows

### ISSUE THREAD

**Issue by SteveEdiger** [chicommons/maps#217]
After installing docker and updating git to the latest version, I successfully cloned maps.git.

When I ran docker-compose up it failed with at 109 (Windows named pipe error: The pipe has ended.

Here is the output just before it started failing:

Image for service apache was built because it did not already exist. To rebuild this image you must use `docker-compose build` or `docker-compose up --build`.
Creating maps_postgres_1 ...
Creating maps_postgres_1 ... done
Creating maps_web_1      ...
Creating maps_web_1      ... done
Creating web-app         ...
Creating web-app         ... done
Creating maps_apache_1   ...
Creating maps_apache_1   ... done
Attaching to maps_postgres_1, maps_web_1, web-app, maps_apache_1
apache_1    | AH00558: httpd: Could not reliably determine the server's fully qualified domain name, using 172.18.0.5. Set the 'ServerName' directive globally to suppress this message
postgres_1  | The files belonging to this database system will be owned by user "postgres".
postgres_1  | This user must also own the server process.
postgres_1  |
postgres_1  | The database cluster will be initialized with locale "en_US.utf8".
postgres_1  | The default database encoding has accordingly been set to "UTF8".
postgres_1  | The default text search configuration will be set to "english".
postgres_1  |
postgres_1  | Data page checksums are disabled.
postgres_1  |
apache_1    | AH00558: httpd: Could not reliably determine the server's fully qualified domain name, using 172.18.0.5. Set the 'ServerName' directive globally to suppress this message
web_1       | Traceback (most recent call last):
web_1       |   File "/usr/local/lib/python3.9/site-packages/django/db/backends/base/base.py", line 219, in ensure_connection
postgres_1  | fixing permissions on existing directory /var/lib/postgresql/data ... ok
web_1       |     self.connect()
web_1       |   File "/usr/local/lib/python3.9/site-packages/django/utils/asyncio.py", line 26, in inner
web_1       |     return func(*args, **kwargs)
web_1       |   File "/usr/local/lib/python3.9/site-packages/django/db/backends/base/base.py", line 200, in connect
postgres_1  | creating subdirectories ... ok
web_1       |     self.connection = self.get_new_connection(conn_params)
web_1       |   File "/usr/local/lib/python3.9/site-packages/django/utils/asyncio.py", line 26, in inner
postgres_1  | selecting default max_connections ... 100
postgres_1  | selecting default shared_buffers ... 128MB
postgres_1  | selecting dynamic shared memory implementation ... posix
postgres_1  | creating configuration files ... ok
apache_1    | [Sat Oct 15 00:14:59.017181 2022] [mpm_event:notice] [pid 1:tid 140705742933312] AH00489: Apache/2.4.54 (Unix) configured -- resuming normal operations
apache_1    | [Sat Oct 15 00:14:59.017324 2022] [core:notice] [pid 1:tid 140705742933312] AH00094: Command line: 'httpd -D FOREGROUND'
web_1       |     return func(*args, **kwargs)
web_1       |   File "/usr/local/lib/python3.9/site-packages/django/db/backends/postgresql/base.py", line 187, in get_new_connection
postgres_1  | running bootstrap script ... ok
postgres_1  | performing post-bootstrap initialization ... ok
web_1       |     connection = Database.connect(**conn_params)
web_1       |   File "/usr/local/lib/python3.9/site-packages/psycopg2/__init__.py", line 127, in connect
postgres_1  | syncing data to disk ... ok
postgres_1  |
postgres_1  | Success. You can now start the database server using:
postgres_1  |
postgres_1  |     pg_ctl -D /var/lib/postgresql/data -l logfile start
postgres_1  |
web_1       |     conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
web_1       | psycopg2.OperationalError: could not connect to server: Connection refused
web_1       |   Is the server running on host "postgres" (172.18.0.2) and accepting
web_1       |   TCP/IP connections on port 5432?
web_1       |
web_1       |
web_1       | The above exception was the direct cause of the following exception:
web_1       |
web_1       | Traceback (most recent call last):
web_1       |   File "/app/manage.py", line 21, in <module>
postgres_1  |
postgres_1  | WARNING: enabling "trust" authentication for local connections
postgres_1  | You can change this by editing pg_hba.conf or using the option -A, or
postgres_1  | --auth-local and --auth-host, the next time you run initdb.
web_1       |     main()
web_1       |   File "/app/manage.py", line 17, in main
web_1       |     execute_from_command_line(sys.argv)
web_1       |   File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
postgres_1  | waiting for server to start....2022-10-15 00:14:57.853 UTC [43] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
postgres_1  | 2022-10-15 00:14:57.877 UTC [44] LOG:  database system was shut down at 2022-10-15 00:14:57 UTC
postgres_1  | 2022-10-15 00:14:57.883 UTC [43] LOG:  database system is ready to accept connections
web_1       |     utility.execute()
web_1       |   File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 395, in execute
postgres_1  |  done
postgres_1  | server started
web_1       |     self.fetch_command(subcommand).run_from_argv(self.argv)
web_1       |   File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 330, in run_from_argv
web_1       |     self.execute(*args, **cmd_options)
web_1       |   File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 371, in execute
postgres_1  | CREATE DATABASE
web_1       |     output = self.handle(*args, **options)
web_1       |   File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 85, in wrapped
postgres_1  |
postgres_1  |
postgres_1  | /usr/local/bin/docker-entrypoint.sh: ignoring /docker-entrypoint-initdb.d/*
postgres_1  |
postgres_1  | waiting for server to shut down...2022-10-15 00:14:58.243 UTC [43] LOG:  received fast shutdown request
web_1       |     res = handle_func(*args, **kwargs)
web_1       |   File "/usr/local/lib/python3.9/site-packages/django/core/management/commands/migrate.py", line 92, in handle
postgres_1  | .2022-10-15 00:14:58.248 UTC [43] LOG:  aborting any active transactions
postgres_1  | 2022-10-15 00:14:58.250 UTC [43] LOG:  worker process: logical replication launcher (PID 50) exited with exit code 1
postgres_1  | 2022-10-15 00:14:58.250 UTC [45] LOG:  shutting down
web_1       |     executor = MigrationExecutor(connection, self.migration_progress_callback)
web_1       |   File "/usr/local/lib/python3.9/site-packages/django/db/migrations/executor.py", line 18, in __init__
web_1       |     self.loader = MigrationLoader(self.connection)
web_1       |   File "/usr/local/lib/python3.9/site-packages/django/db/migrations/loader.py", line 53, in __init__
web_1       |     self.build_graph()
web_1       |   File "/usr/local/lib/python3.9/site-packages/django/db/migrations/loader.py", line 216, in build_graph
postgres_1  | 2022-10-15 00:14:58.290 UTC [43] LOG:  database system is shut down
web_1       |     self.applied_migrations = recorder.applied_migrations()
web_1       |   File "/usr/local/lib/python3.9/site-packages/django/db/migrations/recorder.py", line 77, in applied_migrations
postgres_1  |  done
postgres_1  | server stopped
web_1       |     if self.has_table():
web_1       |   File "/usr/local/lib/python3.9/site-packages/django/db/migrations/recorder.py", line 55, in has_table
postgres_1  |
postgres_1  | PostgreSQL init process complete; ready for start up.
postgres_1  |
web_1       |     with self.connection.cursor() as cursor:
web_1       |   File "/usr/local/lib/python3.9/site-packages/django/utils/asyncio.py", line 26, in inner
postgres_1  | 2022-10-15 00:14:58.354 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
postgres_1  | 2022-10-15 00:14:58.354 UTC [1] LOG:  listening on IPv6 address "::", port 5432
postgres_1  | 2022-10-15 00:14:58.362 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
web_1       |     return func(*args, **kwargs)
web_1       |   File "/usr/local/lib/python3.9/site-packages/django/db/backends/base/base.py", line 259, in cursor
postgres_1  | 2022-10-15 00:14:58.381 UTC [61] LOG:  database system was shut down at 2022-10-15 00:14:58 UTC
postgres_1  | 2022-10-15 00:14:58.389 UTC [1] LOG:  database system is ready to accept connections
web_1       |     return self._cursor()
web_1       |   File "/usr/local/lib/python3.9/site-packages/django/db/backends/base/base.py", line 235, in _cursor
web_1       |     self.ensure_connection()
web_1       |   File "/usr/local/lib/python3.9/site-packages/django/utils/asyncio.py", line 26, in inner
web_1       |     return func(*args, **kwargs)
web_1       |   File "/usr/local/lib/python3.9/site-packages/django/db/backends/base/base.py", line 219, in ensure_connection
web_1       |     self.connect()
web_1       |   File "/usr/local/lib/python3.9/site-packages/django/db/utils.py", line 90, in __exit__
web_1       |     raise dj_exc_value.with_traceback(traceback) from exc_value
web_1       |   File "/usr/local/lib/python3.9/site-packages/django/db/backends/base/base.py", line 219, in ensure_connection
web_1       |     self.connect()
web_1       |   File "/usr/local/lib/python3.9/site-packages/django/utils/asyncio.py", line 26, in inner
web_1       |     return func(*args, **kwargs)
web_1       |   File "/usr/local/lib/python3.9/site-packages/django/db/backends/base/base.py", line 200, in connect
web_1       |     self.connection = self.get_new_connection(conn_params)
web_1       |   File "/usr/local/lib/python3.9/site-packages/django/utils/asyncio.py", line 26, in inner
web_1       |     return func(*args, **kwargs)
web_1       |   File "/usr/local/lib/python3.9/site-packages/django/db/backends/postgresql/base.py", line 187, in get_new_connection
web_1       |     connection = Database.connect(**conn_params)
web_1       |   File "/usr/local/lib/python3.9/site-packages/psycopg2/__init__.py", line 127, in connect
web_1       |     conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
web_1       | django.db.utils.OperationalError: could not connect to server: Connection refused
web_1       |   Is the server running on host "postgres" (172.18.0.2) and accepting
web_1       |   TCP/IP connections on port 5432?
web_1       |
Windows named pipe error: The pipe has been ended. (code: 109)

AzureAD+SteveEdiger@Steve-HP MINGW64 ~/maps (master)
$

**Comment by maxgraziano** [comment]
These issues may be resolved with the recent Docker revisions. @SteveEdiger, would you be able validate?

**Comment by maxgraziano** [comment]
Closed as obsolete.
