### ISSUE TITLE
Front end screen to display coops without coordinates

### ISSUE THREAD

**Issue by laredotornado** [chicommons/maps#23]
We need a new front end screen in the React app that will display coops without latitude and longitude coordinates.  The data is returned by the endpoint

`/coops/no_coords`

The above returns an array of Coop JSON objects, for example

`[{"id": 900, "name": "Dave Coop"}, {"id": 777, "name": "Irving Park Coop"}, ...]`

We simply need a screen to display a list of these coops with an edit icon next to them, similar to the way this is done on the generic search screen ...

<img width="538" alt="Screen Shot 2020-11-27 at 3 10 31 PM" src="https://user-images.githubusercontent.com/14842313/100484639-dfb67f00-30c2-11eb-9e60-8c39f28ee907.png">

that takes an administrator to the edit coop screen, the path to which is

`/edit/:id/home`

where ":id" is the numeric value returned in the "id" attribute of the JSON object above.

**Comment by DaveyDevs** [comment]
@laredotornado  Working on this now! If I'm understanding right, would this be the correct path to search the new endpoint?

const searchUrl = REACT_APP_PROXY + "/coops/no_coords?contains=" + encodeURIComponent(query);

**Comment by laredotornado** [comment]
Hi @DaveyDevs , It is actually even simpler -- you can just write

```
const searchUrl = REACT_APP_PROXY + "/coops/no_coords";
```

At this time, I haven't programmed the ability to search for coops without coordiantes based on a specific string.  The endpoint will just return everything.  We can add that as a separate feature after.

**Comment by DaveyDevs** [comment]
Thanks for the response @laredotornado! 

I just replaced the line in a new component called NoCoordsSearch.jsx and routed it to the page -http://localhost:3000/search_no_coords

It's available for review in a forked branch here - 
https://github.com/DaveyDevs/maps/tree/nocoordinatessearch

Is this the right idea? When I type in the search box, it looks like it's just returning an empty array. Are there any recommendations on next steps so that it return the whole list?

**Comment by laredotornado** [comment]
Hi @DaveyDevs , yes that is the idea.  What you will also want to do is add a Route (e.g. /nocoords) so that we can type a URL in the browser and see the page you created.  This will be probably around line 41 of src/App.js .  Then when you visit http://localhost:3000/nocoords , we should be able to see all the coops that don't have latitude and longitude defined.

If you visit that page and don't see any data, it might be I haven't provided any in the docker database.  I will check on that.

**Comment by DaveyDevs** [comment]
@laredotornado  Done! When you get a chance, would you be able to grant me permissions to publish a branch to the repository? Thanks!

**Comment by laredotornado** [comment]
Hi, You should see a contributor invite in your GitHub account now.  After
you push your branch, please create a pull request so I can look over your
changes and then merge them in.  Thanks! - Dave

**Comment by DaveyDevs** [comment]
@laredotornado  Hey hey! So weirdly I'm not seeing any notification and it won't let me do a direct pull request, but it does list me as a contributor. So I'm not sure what's going on haha. Maybe just an issue with my account, I'll look into it further.

That being said, I was able to create a fork and bring over a pull request through that route. Let me know if that works!

**Comment by laredotornado** [comment]
@DaveyDevs , I pushed the code into production -- https://prod.chicommons.coop/no_coords.  So there is only one more thing to do, which I didn't realize until now.  Instead of having to search for coops without coordinates, we would like them to display automatically as soon as the page is loaded.  I "think" all that is needed is to change this

```
  useEffect(() => {
    if (!searchTerm) {
      setSearchResults([]);
      return;
    }

    // Let the debounced function do it's thing
    const results = doSearchDebounced(searchTerm, setSearchResults, setLoading);
    setSearchResults(results);
  }, [searchTerm]);
```
to
```
  useEffect(() => {
    const results = doSearchDebounced("", setSearchResults, setLoading);
    setSearchResults(results);
  }, []);
```

and also remove this

```
      <h2>Search cooperatives with no coordinates listed:</h2>
      <input
        type="text"
        placeholder="Search"
        value={searchTerm}
        onChange={handleChange}
      />
```

If you update your repository, I have made sure there will be at least one coop without coordinates, so when you fire up docker, this shoudl show at least one result http://localhost:8000/coops/no_coords .  Let me know if this makes sense and/or we coudl discuss more.

**Comment by DaveyDevs** [comment]
@laredotornado  Just completed it and created another pull request, let me know how that looks. Happy holidays!
