### ISSUE TITLE
Backend: Add "is_public" field to ContactMethod model

### ISSUE THREAD

**Issue by laredotornado** [chicommons/maps#36]
You will notice in the web/directory/models.py file, we have a ContactMethod model, looks something like the below ...

```
class ContactMethod(models.Model):
    class ContactTypes(models.TextChoices):
        EMAIL = 'EMAIL', _('Email')
        PHONE = 'PHONE', _('Phone')

    type = models.CharField(
        null=False,
        max_length=5,
        choices=ContactTypes.choices,
    )
    phone = PhoneNumberField(null=True)
    email = models.EmailField(null=True)

    class Meta:
        unique_together = ('phone', 'email',)

```
We need to add a "is_public" boolean attribute (field) to the model to indicate if this information should be displayed.  We then need to generate a migration so this extra column can be added to the database.  In Django, adding a migration looks like

```
. venv/bin/activate # Activate virtual environment
python manage.py makemigration directory   # Create the database script migration
python manage.py migrate directory # Run the database migration

```
Also we need to add this "is_public" field to the test factory classes we use to simulate the models when testing.  This file is tests/factories.py .  The classes to adjust are  PhoneContactMethodFactory and EmailContactMethodFactory .

**Comment by dianakakoma** [comment]
Please assign this issue to me. 
-Diana
