### ISSUE TITLE
Directory entity new request form: Change public labels

### ISSUE THREAD

**Issue by laredotornado** [chicommons/maps#62]
On the directory app new request page

https://prod.chicommons.coop/directory-additions-updates

Instead of just saying 'public', say, 

Is Contact name to be public on the map? 
Is Phone number to be public on the map?
Organization Phone Number 
Is Address to be public on the map? 
Is Email to be public on the map? 

For the fields, "Contact Name Public?", "Phone Public?", "Contact Phone Number", "Address Public?", "Email Public?", respectively.

**Comment by DaveyDevs** [comment]
comment
