### ISSUE TITLE
Frontend: App name incorrectly displays as "React App" in browser header

### ISSUE THREAD

**Issue by laredotornado** [chicommons/maps#71]
Title appears as "React App"

![Screen Shot 2021-05-21 at 8 04 55 AM](https://user-images.githubusercontent.com/14842313/119142178-cb1cc900-ba0b-11eb-92fd-4ca4c6cf15c9.png)

but the desire is for the title to appear as "CoOp Map".

**Comment by ozzysChiefDataScientist** [comment]
I submitted a PR on this issue here: https://github.com/chicommons/maps/pull/83
