### ISSUE TITLE
Frontend: Make "Search" link to "Advanced Search"

### ISSUE THREAD

**Issue by laredotornado** [chicommons/maps#72]
On the main menu, the "Search" nav item should link to the same component linked to by

https://prod.chicommons.coop/advanced

and the "Advanced Search" item should disappear.  Clicking "Search" should still route to

https://prod.chicommons.coop/search

but the component that renders should be the advanced search component.

**Comment by ozzysChiefDataScientist** [comment]
@laredotornado  Can you assign this to me? thanks.

**Comment by laredotornado** [comment]
Done!  Left one comment on your PR.  Thanks for looking into this, -
