### ISSUE TITLE
Frontend: update advanced search coop-type field to be a multi-select field

### ISSUE THREAD

**Issue by laredotornado** [chicommons/maps#73]
The coop type field on 

https://prod.chicommons.coop/advanced

is currently single select.  We would like to make it multi-select, similar to the multi-select here

https://prod.chicommons.coop/directory-additions-updates

It would be enough to re-use the component on the directory-additions-updates page on this page.  The value of the data submitted should be an array, 

```
['Community Garden', 'Credit Union']
```

as an example. 

Also update the label to read "CoOp Type".

**Comment by kevinjung2** [comment]
I can take this one
