### ISSUE TITLE
Frontend: Add county and state to search form

### ISSUE THREAD

**Issue by laredotornado** [chicommons/maps#74]
Currently here

https://prod.chicommons.coop/advanced

under "Postal Code", we need to add two additional search fields, "County" (a text field) and State, a single select drop down field, as seen here

https://prod.chicommons.coop/add

The field names in the search can be "county" and "state".

**Comment by ozzysChiefDataScientist** [comment]
@laredotornado Can you assign this to me? Thanks.

**Comment by ozzysChiefDataScientist** [comment]
Submitted PR: https://github.com/chicommons/maps/pull/86

**Comment by laredotornado** [comment]
merged
