### ISSUE TITLE
Frontend: Change link location where advanced search results "edit" icon links to

### ISSUE THREAD

**Issue by laredotornado** [chicommons/maps#77]
When doing an advanced search here

https://prod.chicommons.coop/advanced

we need to change the location at which the "edit" icon points

<img width="487" alt="Screen Shot 2021-06-01 at 9 04 26 PM" src="https://user-images.githubusercontent.com/14842313/120413013-29f01580-c31d-11eb-93bb-a2c87d8aaa45.png">

https://prod.chicommons.coop/directory-additions-updates/{id}

where ID is the Id of that particular result.

**Comment by ozzysChiefDataScientist** [comment]
@laredotornado Can you assign this to me?
