### ISSUE TITLE
Frontend: Need to expand directory addition page to preload data with from an ID

### ISSUE THREAD

**Issue by laredotornado** [chicommons/maps#79]
The directory page located at 

https://prod.chicommons.coop/directory-additions-updates

needs to accept an ID, which will reference a directory coop from the database.  The link should look like

https://prod.chicommons.coop/directory-additions-updates/{id}

The ID should load its data from the backend via the URL

https://prod.chicommons.coop/coops/{id}/

The data will be returned looking like below

```
{"id":1,"types":[{"id":1,"name":"Coworking Space"}],"addresses":[{"id":1,"street_number":"222","route":"1212","raw":"222 W. Merchandise Mart Plaza, Suite 1212","formatted":"222 W. Merchandise Mart Plaza, Suite 1212","latitude":41.88802611,"longitude":-87.63612199,"locality":{"id":74,"name":"Chicago","postal_code":"60654","state":{"id":19313,"code":"IL","name":"Illinois","country":{"id":484,"name":"United States","code":"US"}}}}],"phone":null,"email":null,"name":"1871","enabled":true,"web_site":"http://www.1871.com/"}
```

We will want to preload the fields on the directory addition form with the data available from above.

**Comment by DaveyDevs** [comment]
Just created a pull request for this issue - #91
