### ISSUE TITLE
FrontEnd: Change "Add" link in nav bar

### ISSUE THREAD

**Issue by laredotornado** [chicommons/maps#87]
We need to point the "Add" link on the nav bar to

https://prod.chicommons.coop/directory-additions-updates

**Comment by carltos0411** [comment]
Hey @laredotornado  i want to work on this issue as i am beginner pls guide me a little bit

**Comment by ozzysChiefDataScientist** [comment]
@laredotornado I submitted a PR on this here: https://github.com/chicommons/maps/pull/97

**Comment by laredotornado** [comment]
Thanks!  This is merged.
