### ISSUE TITLE
FrontEnd: Create "Home" link in nav bar with iframe content

### ISSUE THREAD

**Issue by laredotornado** [chicommons/maps#88]
In the main nav bar, to the left of "Add," we need to add a "Home" link that will take us to a new component that will display our map (content from an iframe).  The route of the component shoudl be the default route "/".  The content is

<iframe width="100%" height="300px" frameborder="0" allowfullscreen src="//umap.openstreetmap.fr/en/map/chicommons-map_80079?scaleControl=false&miniMap=false&scrollWheelZoom=false&zoomControl=true&allowEdit=false&moreControl=true&searchControl=null&tilelayersControl=null&embedControl=null&datalayersControl=true&onLoadPanel=caption&captionBar=false"></iframe><p><a href="//umap.openstreetmap.fr/en/map/chicommons-map_80079">See full screen</a></p>

For now it is fine that the height is a fixed pixel width, but it would be nice if there were some way to adjust this to fit the various screens you are on.  

We are essentially trying to duplicate the map content on this page

https://www.chicommons.coop/cooperative-map/

**Comment by DaveyDevs** [comment]
Just created a pull request for this issue!

**Comment by laredotornado** [comment]
Thanks!  Left a couple of small comments.

**Comment by SteveEdiger** [comment]
Make iFrame full screen for all viewport size

**Comment by SteveEdiger** [comment]
Make it full screen, and get rid  of Open in Full screen button

**Comment by DaveyDevs** [comment]
Just updated and created a pull request! I wasn't able to make the full width but got the closest I could without interfering with the vertical scroll in the guide that initially shows up when the map loads.

**Comment by DaveyDevs** [comment]
Steve requested we center the map iframe. I can take care of that. 👍

**Comment by DaveyDevs** [comment]
Just updated the CSS and created a pull request!
