### ISSUE TITLE
FrontEnd: Remove "Bad Location" from nav bar

### ISSUE THREAD

**Issue by laredotornado** [chicommons/maps#89]
Currently on the nav bar there is a "Bad Location" item (the last one)

https://prod.chicommons.coop/add

we wish to remove the item from the nav bar (but the route can remain).

**Comment by carltos0411** [comment]
@laredotornado  pls assign this issue to me

**Comment by ozzysChiefDataScientist** [comment]
@laredotornado Can you assign to me?

**Comment by laredotornado** [comment]
Posterity will not that @ozzysChiefDataScientist  created a PR for this and it has merged.  Will haev @SteveEdiger  review before closing.
