### ISSUE TITLE
FrontEnd: Add "Return" item to nav bar

### ISSUE THREAD

**Issue by laredotornado** [chicommons/maps#90]
On our current set up

https://prod.chicommons.coop/add

we wish to add a "Return" link as the last item on the nav bar.  This should take the user off our directory site and link them to https://www.chicommons.coop/cooperative-map/

**Comment by DaveyDevs** [comment]
Just added a "return" link to the nav and hamburger bar and created a pull request. I also noticed that the hamburger menu was hidden behind some of the containers on pages, so I added z-index to put it above in each of the views.
