### ISSUE TITLE
FrontEnd: Adjust typography and colors to match style guide

### ISSUE THREAD

**Issue by laredotornado** [chicommons/maps#93]
[CCC-Style Guide-Ver 1.0.pdf](https://github.com/chicommons/maps/files/6652161/CCC-Style.Guide-Ver.1.0.pdf)

We need to apply pages 6 (typography) and 7 (colors) of the attached style guide globally to the site.

**Comment by nick-hou** [comment]
Can you assign this one to me? Thanks

**Comment by laredotornado** [comment]
A few notes from @SteveEdiger , sent vis email ...

General

- <h1>-<h6> should be Alegreya-Sans. All other text should be Ubuntu
- We don't use gradients anywhere.
- I'm not sure what the max-width is currently set at on the largest displays, but we should pick one (probably the one we are using now and make that the site width (see 2.3 and 3.1).  If this is too wide, the eye loses itself across long text lines.  If it's too narrow, we are not using all available horizontal space.

Header (and Footer when we get one)

- The background color should be #f6fbfb, no gradient
- The nav-menu font should be Alegreya-Sans, weight 400
- Please limit the header width to the active screen width and make the area outside of that, white (#ffffff)*.  Nogradients
- As per 1.2 and 2.3, the header elements (logo on the left and nav-bar on the right) should be within that screen width.

Body

- Please change color to white outside the active screen elements*


Forms

- No radius on the form corners
- See 1.1 above. Both field labels and text should be Ubuntu.
- Data entry fields should have #f6fbfb as their background.
- I'm not sure I like the 500 weight on the field labels, but let me check it after I see it in Ubuntu typeface.
